version: "3.9"


services:
  db:
    image: mysql:9
    container_name: mysql_cont
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${MY_TODO_DB}
      MYSQL_USER: user
      MYSQL_PASSWORD: ${USER_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: todoAPP_main
    command: fastapi run main_app/main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  db_data:
