version: "3.8"

services:
  school_manager_app.api:
    build: .
    container_name: school_manager_cont
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - FORWARD_DB_PORT=${FORWARD_DB_PORT}
    volumes:
      - ./app:/app/app
